name: CI

# Triggers whenever a new commit is pushed or a new pull request
on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches: 
      - main
      - test

jobs:
  test:
    strategy:
      # So that fails do not cascade
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11]

    name: Route Test

    # Use operating systems defined in matrix
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        # Multi line string - executes together
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        # Define environmental variables from repo secrets
        env:
            MODE: ${{ vars.MODE }}
            DATABASE_URL_TEST: ${{ secrets.DATABASE_URL_TEST }}

        run: pytest tests/
